# Generated by Django 4.0.4 on 2022-05-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordMeaning',
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
