# Generated by Django 4.0.4 on 2022-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmeaning',
            name='priority',
            field=models.IntegerField(blank=True),
        ),
    ]
